const MSI_CATALOG = [
  {
    id: 'ip-15-pro-max-256-tit-nat',
    name: 'iPhone 17 Pro Max',
    storage: '256GB',
    condition: 'Seminovo Certificado',
    batteryHealth: 96,
    price: 7899.0,
    originalPrice: 9499.0,
    installments: 12,
    isNew: false,
    isFeatured: true,
    badge: 'Top Pick',
    colorOptions: [
      { name: 'Branco',  hex: '#e7e6e1', image: 'assets/images/products/iphone15/iphone17promax/iphone17promax.branco-removebg-preview.png' },
      { name: 'Azul',    hex: '#3e4a5c', image: 'assets/images/products/iphone15/iphone17promax/iphone17proxmax.azul-removebg-preview.png' },
      { name: 'Laranja', hex: '#d4612a', image: 'assets/images/products/iphone15/iphone17promax/iphone17.promax-removebg-preview.png' },
    ],
    accent: '#bdb4a5',
    deviceTone: 'titanium-natural',
  },
  {
    id: 'ip-16-pro-512-des-tit',
    name: 'iPhone 16 Pro Max',
    storage: '512GB',
    condition: 'Novo · Lacrado',
    batteryHealth: 100,
    price: 9299.0,
    originalPrice: 10499.0,
    installments: 12,
    isNew: true,
    isFeatured: true,
    badge: 'Lacrado',
    colorOptions: [
      { name: 'Titânio Deserto', hex: '#b9a487', image: 'assets/images/products/iphone15/iphone16promax/iphone16promax.titanio-removebg-preview.png' },
      { name: 'Titânio Natural', hex: '#c9bfae', image: 'assets/images/products/iphone15/iphone16promax/iphone15promax.titanio.natura-removebg-preview.png' },
    ],
    accent: '#b9a487',
    deviceTone: 'titanium-desert',
  },
  {
    id: 'ip-14-128-roxo',
    name: 'iPhone 14',
    storage: '128GB',
    condition: 'Seminovo Certificado',
    batteryHealth: 89,
    price: 3499.0,
    originalPrice: 4799.0,
    installments: 10,
    isNew: false,
    badge: 'Bateria 89%',
    colorOptions: [
      { name: 'Vermelho',    hex: '#bb1c33', image: 'assets/images/products/iphone15/iphone14/iphone14.vermelho-removebg-preview.png' },
      { name: 'Branco',      hex: '#f1efe7', image: 'assets/images/products/iphone15/iphone14/iphone14.branco-removebg-preview.png' },
      { name: 'Azul Estelar',hex: '#3e4a5c', image: 'assets/images/products/iphone15/iphone14/iphone14.azul.estelar.png' },
      { name: 'Amarelo',     hex: '#f5d547', image: 'assets/images/products/iphone15/iphone14/iphone14.amarelo-removebg-preview.png' },
    ],
    accent: '#bb1c33',
    deviceTone: 'lavender',
  },
  {
    id: 'ip-13-mini-128-rosa',
    name: 'iPhone 13',
    storage: '128GB',
    condition: 'Seminovo Certificado',
    batteryHealth: 91,
    price: 2299.0,
    originalPrice: 3299.0,
    installments: 8,
    isNew: false,
    badge: 'Oferta',
    colorOptions: [
      { name: 'Branco', hex: '#f1efe7', image: 'assets/images/products/iphone15/iphone13/iphone13.branco-removebg-preview.png' },
      { name: 'Azul Estelar', hex: '#1c2535', image: 'assets/images/products/iphone15/iphone13/iphone13.preto-removebg-preview.png' },
    ],
    accent: '#f4d3d2',
    deviceTone: 'pink',
  },
  {
    id: 'ip-15-256-azul',
    name: 'iPhone 15',
    storage: '256GB',
    condition: 'Seminovo Certificado',
    batteryHealth: 94,
    price: 4799.0,
    originalPrice: 6299.0,
    installments: 12,
    isNew: false,
    badge: 'Bateria 94%',
    colorOptions: [
      { name: 'Azul',    hex: '#c9dee8', image: 'assets/images/products/iphone15/iphone15.azul-removebg-preview.png' },
      { name: 'Amarelo', hex: '#f0dfa3', image: 'assets/images/products/iphone15/iphone15.amarelo-removebg-preview.png' },
      { name: 'Preto',   hex: '#1d1f24', image: 'assets/images/products/iphone15/iphone15.preto-removebg-preview.png' },
    ],
    accent: '#c9dee8',
    deviceTone: 'blue',
  },
  {
    id: 'ip-16-128-tit-verde',
    name: 'iPhone 16',
    storage: '128GB',
    condition: 'Novo · Lacrado',
    batteryHealth: 100,
    price: 5899.0,
    originalPrice: 6999.0,
    installments: 12,
    isNew: true,
    badge: 'Lacrado',
    colorOptions: [
      { name: 'Verde-acinzentado', hex: '#a7b3a4', image: 'assets/images/products/iphone15/iphone16/iphone16.verde.acinzentado-removebg-preview.png' },
      { name: 'Rosa',              hex: '#f4d3d2', image: 'assets/images/products/iphone15/iphone16/iphone16.rosa-removebg-preview.png' },
      { name: 'Branco',            hex: '#ecebe6', image: 'assets/images/products/iphone15/iphone16/iphone16.branco-removebg-preview.png' },
      { name: 'Ultramarino',       hex: '#4b5b8c', image: 'assets/images/products/iphone15/iphone16/iphone16.ultramarino-removebg-preview.png' },
      { name: 'Preto',             hex: '#1d1f24', image: 'assets/images/products/iphone15/iphone16/iphone16.preto-removebg-preview.png' },
    ],
    accent: '#a7b3a4',
    deviceTone: 'green',
  },
];

const MSI_FAQ = [
  {
    q: 'Como vocês garantem que o iPhone seminovo é confiável?',
    a: 'Todo aparelho passa por um diagnóstico de 47 pontos, IMEI verificado na operadora, saúde de bateria igual ou superior a 85% e teste de todos os sensores. Você recebe um laudo técnico junto do aparelho.',
  },
  {
    q: 'Como funciona o trade-in?',
    a: 'Você nos envia o modelo, saúde de bateria e estado de conservação. Em até 10 minutos retornamos com uma faixa de avaliação. Se aceitar, agendamos a coleta e o valor entra como crédito no novo aparelho.',
  },
  {
    q: 'Quais são as formas de pagamento?',
    a: 'PIX (com 5% de desconto), cartão de crédito em até 12x sem juros, boleto e financiamento direto. Aparelhos acima de R$ 5.000 contam com seguro de transporte incluso.',
  },
  {
    q: 'Qual é a garantia dos aparelhos?',
    a: 'Novos lacrados: 12 meses Apple + 3 meses msiphone. Seminovos certificados: 90 dias de garantia total msiphone cobrindo defeitos de fábrica e bateria.',
  },
  {
    q: 'Vocês entregam para todo o Brasil?',
    a: 'Sim. Capitais em até 2 dias úteis e interior em até 5 dias. Envio com rastreio em tempo real e seguro contra extravio sem custo adicional.',
  },
  {
    q: 'Posso vender meu iPhone sem comprar outro?',
    a: 'Pode. Fazemos a compra à vista via PIX no mesmo dia em que recebemos e aprovamos o aparelho. Sem letras miúdas.',
  },
];

Object.assign(window, { MSI_CATALOG, MSI_FAQ });
